/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1.edd.pkg201222576;

import java.io.File;
import java.io.FileWriter;

/**
 *
 * @author Breynner
 */
public class PruebaGraphiz extends javax.swing.JFrame {

    /**
     * Creates new form PruebaGraphiz
     */
    public PruebaGraphiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton1)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton1)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                    try
              {
               File archivo=new File("C:\\Users\\Breynner\\Desktop\\texto.txt");
               FileWriter escribir=new FileWriter(archivo,true);
               escribir.write("digraph g{\n" +
"node[shape=record]\n" +
"uno[label=\"<f0>|<f1>1|<f2>\"];\n" +
"dos[label=\"<f0>|<f1>2|<f2>\"];\n" +
"tres[label=\"<f0>|<f1>3|<f2>\"];\n" +
"cuatro[label=\"<f0>|<f1>4|<f2>\"];\n" +
"cinco[label=\"<f0>|<f1>5|<f2>\"];\n" +
"seis[label=\"<f0>|<f1>6|<f2>\"];\n" +
"siete[label=\"<f0>|<f1>7|<f2>\"];\n" +
"ocho[label=\"<f0>|<f1>8|<f2>\"];\n" +
"nueve[label=\"<f0>|<f1>9|<f2>\"];\n" +
"nulo1;\n" +
"nulo2;\n" +
"nulo3;\n" +
"ranksep = .5; splines=ortho;\n" +
"{\n" +
"node [shape = record ];\n" +
"uno->cuatro ->siete;\n" +
"siete->cuatro->uno\n" +
"}\n" +
"\n" +
"{\n" +
"rank = same;\n" +
"uno:f2 -> dos:f0;dos:f0 -> uno:f2;\n" +
"dos:f2 -> tres:f0;tres:f0 -> dos:f2;\n" +
"tres:f2 -> nulo1;\n" +
"}\n" +
"\n" +
"{\n" +
"rank = same;\n" +
"cuatro:f2 -> cinco:f0;cinco:f0 -> cuatro:f2;\n" +
"cinco:f2 -> seis:f0;seis:f0 -> cinco:f2;\n" +
"seis:f2 -> nulo2;\n" +
"}\n" +
"{\n" +
"rank = same;\n" +
"siete:f2 -> ocho:f0;ocho:f0 -> siete:f2;\n" +
"ocho:f2 -> nueve:f0;nueve:f0 -> ocho:f2;\n" +
"nueve:f2 -> nulo3;\n" +
"}\n" +
"\n" +
"}");
               escribir.close();
              }

              //Si existe un problema al escribir cae aqui
              catch(Exception e)
              {
              System.out.println("Error al escribir");
              }
        
        
        
        try {
      
      String dotPath = "C:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe";
      
      String fileInputPath = "C:\\Users\\Breynner\\Desktop\\pruebaeddlista.txt";
      String fileOutputPath = "C:\\Users\\Breynner\\Desktop\\pruebaeddlista.jpg";
      
      String tParam = "-Tjpg";
      String tOParam = "-o";
        
      String[] cmd = new String[5];
      cmd[0] = dotPath;
      cmd[1] = tParam;
      cmd[2] = fileInputPath;
      cmd[3] = tOParam;
      cmd[4] = fileOutputPath;
                  
      Runtime rt = Runtime.getRuntime();
      
      rt.exec( cmd );
      
    } catch (Exception ex) {
      ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaGraphiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaGraphiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaGraphiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaGraphiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaGraphiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
